# Generated by Django 4.2.1 on 2023-05-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(default='img.jpg', upload_to='article_images/', verbose_name='Зображення'),
        ),
    ]
